import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'vi' | 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    'menu.dashboard': 'Bảng điều khiển',
    'menu.admin': 'Quản trị',
    'menu.settings': 'Cài đặt',
    'chatbot.title': 'Trợ lý AI Doanh nghiệp',
    'chatbot.placeholder': 'Nhập tin nhắn...',
    'chatbot.send': 'Gửi',
    'home.announcements': 'Thông báo quan trọng',
    'home.todo': 'Việc cần làm',
    'home.calendar': 'Lịch trình',
    'home.quickAccess': 'Lối tắt',
    'home.lineConnect': 'Kết nối Line',
    'dashboard.finance': 'Tài chính',
    'dashboard.operations': 'Vận hành & Thị trường',
    'dashboard.hr': 'Nhân sự & DX',
    'admin.users': 'Quản lý người dùng',
    'admin.data': 'Dữ liệu & RAG',
    'admin.master': 'Danh mục Master',
    'admin.approval': 'Phê duyệt (Ringi-sho)',
    'admin.botSettings': 'Cài đặt AI Bot',
    'admin.integrations': 'Kết nối ứng dụng',
    'admin.audit': 'Lịch sử hệ thống',
    'messages.internal': 'Hộp thư nội bộ',
    'messages.feedback': 'Phản hồi khách hàng',
    'messages.emergency': 'Liên lạc khẩn cấp',
    'messages.files': 'Lưu trữ tài liệu',
    'settings.profile': 'Hồ sơ doanh nghiệp',
    'settings.goals': 'Thiết lập mục tiêu',
    'settings.notifications': 'Cấu hình thông báo',
    'settings.security': 'Bảo mật & Ngôn ngữ',
    'auth.changePassword': 'Đổi mật khẩu',
    'auth.logout': 'Đăng xuất',
    'auth.currentPassword': 'Mật khẩu hiện tại',
    'auth.newPassword': 'Mật khẩu mới',
    'auth.confirmPassword': 'Xác nhận mật khẩu mới',
    'auth.cancel': 'Hủy',
    'auth.update': 'Cập nhật',
    'auth.passwordMismatch': 'Mật khẩu mới không khớp.',
    'auth.passwordLength': 'Mật khẩu mới phải có ít nhất 6 ký tự.',
    'auth.passwordSuccess': 'Đổi mật khẩu thành công!',
    'dashboard.searchAccounts': 'Tài khoản',
    'dashboard.searchDeals': 'Giao dịch',
    'dashboard.searchTechFlowEnt': 'Doanh nghiệp TechFlow',
    'dashboard.searchTechFlowQ3': 'Mở rộng TechFlow Q3',
    'login.title': 'Nippon DX Platform',
    'login.subtitle': 'Đăng nhập vào hệ thống quản trị',
    'login.email': 'Địa chỉ Email',
    'login.password': 'Mật khẩu',
    'login.forgotPassword': 'Quên mật khẩu?',
    'login.signIn': 'Đăng nhập',
    'login.signingIn': 'Đang đăng nhập...',
    'login.rememberMe': 'Ghi nhớ đăng nhập',
    'login.error': 'Email hoặc mật khẩu không đúng',
    'dashboard.proactiveMessage': 'Tôi đã chuẩn bị một kế hoạch phục hồi và xác định 3 giao dịch có rủi ro.',
    'dashboard.search': 'Tìm kiếm...',
    'dashboard.askAgent': 'Hỏi AI',
    'dashboard.notifications': 'Thông báo',
    'dashboard.markAllRead': 'Đánh dấu đã đọc',
    'dashboard.overview': 'Tổng quan',
    'dashboard.revenue': 'Doanh thu',
    'dashboard.pipeline': 'Đường ống',
    'dashboard.accounts': 'Khách hàng',
    'dashboard.pnl': 'Lãi/Lỗ',
    'dashboard.reports': 'Báo cáo',
    'dashboard.month': 'Tháng',
    'dashboard.quarter': 'Quý',
    'dashboard.year': 'Năm',
    'dashboard.allTeams': 'Tất cả nhóm',
    'dashboard.allAccounts': 'Tất cả khách hàng',
    'dashboard.keyAccounts': 'Khách hàng VIP',
    'dashboard.standardAccounts': 'Khách hàng thường',
    'dashboard.revenueYTD': 'Doanh thu YTD',
    'dashboard.vsTarget': 'So với mục tiêu',
    'dashboard.pipelineValue': 'Giá trị đường ống',
    'dashboard.winRate': 'Tỷ lệ thắng',
    'dashboard.activeAccounts': 'Khách hàng hoạt động',
    'dashboard.churnRate': 'Tỷ lệ rời bỏ',
    'dashboard.grossMargin': 'Biên lợi nhuận gộp',
    'dashboard.vsLastYear': 'So với năm trước',
    'dashboard.recentActivity': 'Hoạt động gần đây',
    'dashboard.upcomingRenewals': 'Gia hạn sắp tới',
    'dashboard.topPerformers': 'Nhân viên xuất sắc',
    'dashboard.addWidget': 'Thêm Widget',
    'dashboard.grossProfit': 'Lợi nhuận gộp',
    'dashboard.achievement': '% Đạt được',
    'dashboard.growthYoY': 'Tăng trưởng YoY',
    'dashboard.wipVsPlan': 'So sánh Thực tế vs Kế hoạch',
    'dashboard.wipActual': 'Thực tế (WIP)',
    'dashboard.plan': 'Kế hoạch',
    'dashboard.vsLastMonth': 'So với tháng trước',
    'dashboard.vsPlan': 'So với kế hoạch',
    'dashboard.salesFunnel': 'Phễu Bán hàng & Hiệu suất',
    'dashboard.salesPipelineFunnel': 'Phễu Đường ống Bán hàng',
    'dashboard.conversionRate': 'Tỷ lệ Chuyển đổi theo Tháng (%)',
    'dashboard.perfByLeadSource': 'Hiệu suất theo Nguồn Khách hàng',
    'dashboard.perfBySalesRep': 'Hiệu suất theo Nhân viên Bán hàng',
    'dashboard.agentInsights': 'Thông tin chi tiết từ Agent & Hành động Đề xuất',
    'dashboard.updatedAgo': 'Cập nhật 5 phút trước',
    'dashboard.generateReport': 'Tạo Báo cáo Hàng tuần',
    'dashboard.createRecoveryPlan': 'Tạo Kế hoạch Phục hồi',
    'dashboard.sendFollowUps': 'Gửi Bản nháp Theo dõi',
    'dashboard.simulateRevenueDrop': 'Mô phỏng Giảm Doanh thu',
    'dashboard.insight1': 'Gap 12.4M JPY chủ yếu do 3 deals slipped ở khu vực Osaka.',
    'dashboard.insight2': 'WIP: 7 deals đang quá hạn next step (Kenji Sato: 4, Yumi Tanaka: 3).',
    'dashboard.insight3': 'TechFlow Enterprise có tín hiệu tốt từ email gần nhất, khả năng close trong tuần này.',
    'dashboard.notif1Title': 'Deal có nguy cơ',
    'dashboard.notif1Desc': 'Biên lợi nhuận của Acme Corp Upgrade giảm xuống dưới 25%.',
    'dashboard.notif1Time': '10 phút trước',
    'dashboard.notif2Title': 'Đã tạo báo cáo',
    'dashboard.notif2Desc': 'Báo cáo Bán hàng Hàng tuần đã sẵn sàng để xem xét.',
    'dashboard.notif2Time': '2 giờ trước',
    'dashboard.viewAll': 'Xem tất cả',
    'dashboard.views.backToDashboard': 'Quay lại Bảng điều khiển',
    'dashboard.views.revenueAnalysis': 'Phân tích Doanh thu',
    'dashboard.views.month': 'Tháng',
    'dashboard.views.quarter': 'Quý',
    'dashboard.views.ytd': 'Từ đầu năm',
    'dashboard.views.byTeam': 'Theo Nhóm',
    'dashboard.views.byProduct': 'Theo Sản phẩm',
    'dashboard.views.byAccount': 'Theo Tài khoản',
    'dashboard.views.planVsActual': 'Kế hoạch vs Thực tế',
    'dashboard.views.segment': 'Phân khúc',
    'dashboard.views.plan': 'Kế hoạch',
    'dashboard.views.actual': 'Thực tế',
    'dashboard.views.gap': 'Chênh lệch',
    'dashboard.views.attainment': '% Đạt được',
    'dashboard.views.forecastEOM': 'Dự báo cuối tháng',
    'dashboard.views.confidence': 'Độ tin cậy',
    'dashboard.views.gapExplorer': 'Khám phá Chênh lệch',
    'dashboard.views.slippedDeals': 'Giao dịch bị trượt',
    'dashboard.views.reason': 'Lý do',
    'dashboard.views.createTask': 'Tạo công việc',
    'dashboard.views.lowPipeline': 'Độ phủ Pipeline thấp',
    'dashboard.views.target': 'Mục tiêu',
    'industry.mfg': 'Sản xuất',
    'industry.whl': 'Bán buôn',
    'industry.rtl': 'Bán lẻ',
    'industry.con': 'Xây dựng',
    'industry.it': 'CNTT / Phần mềm',
    'industry.log': 'Logistics',
    'industry.pro': 'Dịch vụ Chuyên nghiệp',
    'industry.hos': 'Nhà hàng / Khách sạn',
    'industry.hlt': 'Chăm sóc Sức khỏe',
    'industry.real': 'Bất động sản',
    'industry.edu': 'Giáo dục',
    'industry.agr': 'Nông nghiệp / Thực phẩm',
    'industry.psv': 'Dịch vụ Cá nhân',
    'industry.ecom': 'Thương mại Điện tử',
    'admin.title': 'Quản trị hệ thống',
    'admin.desc': 'Cấu hình và quản lý hệ thống.',
    'admin.companyProfile': 'Hồ sơ công ty',
    'admin.companyProfileDesc': 'Quản lý cài đặt tenant và ngành nghề',
    'admin.dashboardConfig': 'Cấu hình Dashboard',
    'admin.dashboardConfigDesc': 'Cấu hình mẫu KPI theo ngành',
    'admin.usersDesc': 'Quản lý vai trò và quyền hạn',
    'admin.dataDesc': 'Tải tài liệu huấn luyện AI',
    'admin.botSettingsDesc': 'Cấu hình hành vi và giọng điệu AI',
    'admin.integrationsDesc': 'Line, Kintone, Salesforce',
    'admin.manage': 'Quản lý',
    'admin.backToAdmin': 'Quay lại Quản trị',
    'admin.saveChanges': 'Lưu thay đổi',
    'admin.cancel': 'Hủy',
    'admin.companyName': 'Tên công ty',
    'admin.industry': 'Ngành nghề',
    'admin.industryWarning': 'Thay đổi ngành nghề sẽ đặt lại cấu hình Dashboard Builder.',
    'admin.searchUsers': 'Tìm kiếm người dùng theo tên hoặc email...',
    'admin.addUser': 'Thêm người dùng',
    'admin.user': 'Người dùng',
    'admin.roleDept': 'Vai trò & Phòng ban',
    'admin.status': 'Trạng thái',
    'admin.lastLogin': 'Đăng nhập lần cuối',
    'admin.actions': 'Hành động',
    'admin.dataSources': 'Nguồn dữ liệu',
    'admin.agentTraining': 'Agent học dữ liệu',
    'admin.dashboardConfigTab': 'Cấu hình Dashboard',
    'admin.uploadDesc': 'Tải lên file hoặc kết nối cơ sở dữ liệu để Agent có thể học và phân tích.',
    'admin.connectDB': 'Kết nối Database/API',
    'admin.uploading': 'Đang tải lên & Xử lý...',
    'admin.uploadData': 'Tải lên dữ liệu (PDF, CSV, Excel)',
    'admin.dragDrop': 'Kéo thả file vào đây hoặc click để chọn. Hỗ trợ mọi loại bảng biểu và tài liệu.',
    'admin.dataSourceList': 'Danh sách nguồn dữ liệu',
    'admin.records': 'bản ghi',
    'admin.trainingDesc': 'Quản lý cách Agent hiểu và trích xuất cấu trúc từ dữ liệu của bạn.',
    'admin.retrainAll': 'Huấn luyện lại tất cả',
    'admin.source': 'Nguồn',
    'admin.unknown': 'Không xác định',
    'admin.accuracy': 'Độ chính xác',
    'admin.editSchema': 'Chỉnh sửa Schema',
    'admin.detectedFields': 'Trường dữ liệu nhận diện được:',
    'admin.addField': 'Thêm trường',
    'admin.mappingDesc': 'Ánh xạ dữ liệu Agent đã học vào các Template Dashboard.',
    'admin.createNewMapping': 'Tạo Mapping mới',
    'admin.autoMap': 'Auto Map',
    'admin.sync': 'Đồng bộ',
    'admin.integrationsDesc': 'Kết nối các ứng dụng của bên thứ ba để đồng bộ hóa dữ liệu và kích hoạt các tính năng đa nền tảng.',
    'admin.connect': 'Kết nối',
    'admin.disconnect': 'Ngắt kết nối',
    'admin.aiAgentStudio': 'AI Agent Studio',
    'admin.aiAgentDesc': 'Quản lý các AI Agent chuyên biệt, kiến thức và hành vi của chúng.',
    'admin.createAgent': 'Tạo Agent',
    'admin.tasksAutomated': 'tác vụ tự động',
    'admin.proactiveTriggers': 'Kích hoạt chủ động',
    'admin.proactiveDesc': 'Khác với chatbot thụ động, Agent của chúng tôi theo dõi dữ liệu của bạn và tự động bắt đầu các hành động.',
    'admin.configureTriggers': 'Cấu hình kích hoạt',
    'admin.jpContextTuning': 'Tinh chỉnh ngữ cảnh tiếng Nhật',
    'admin.keigoLevel': 'Mức độ Keigo (Mặc định)',
    'admin.industryJargon': 'Thuật ngữ chuyên ngành',
    'admin.editUser': 'Chỉnh sửa người dùng',
    'admin.addNewUser': 'Thêm người dùng mới',
    'admin.fullName': 'Họ và tên',
    'admin.emailAddress': 'Địa chỉ Email',
    'admin.department': 'Phòng ban',
    'admin.role': 'Vai trò',
    'admin.status': 'Trạng thái',
    'admin.resetPassword': 'Đặt lại mật khẩu (Tùy chọn)',
    'admin.initialPassword': 'Mật khẩu ban đầu',
    'admin.leaveBlank': 'Để trống để giữ nguyên',
    'admin.enterPassword': 'Nhập mật khẩu',
    'admin.modulePermissions': 'Quyền truy cập Module',
    'admin.adminAccessNote': 'Admin tự động có toàn quyền truy cập vào tất cả các module.',
    'admin.saveUser': 'Lưu người dùng',
    'admin.cancel': 'Hủy',
    'admin.connectDBAPI': 'Kết nối Database/API',
    'admin.connectionType': 'Loại kết nối',
    'admin.displayName': 'Tên hiển thị',
    'admin.connectionString': 'Connection String / URL',
    'admin.connectBtn': 'Kết nối',
    'admin.addSchemaField': 'Thêm trường Schema',
    'admin.fieldName': 'Tên trường',
    'admin.fieldType': 'Kiểu dữ liệu',
    'admin.description': 'Mô tả',
    'admin.addBtn': 'Thêm',
    'admin.createMapping': 'Tạo Mapping',
    'admin.selectSchema': 'Chọn Schema',
    'admin.selectTemplate': 'Chọn Template',
    'admin.createBtn': 'Tạo',
    'admin.companySaved': 'Cài đặt công ty đã được lưu thành công. KPI Dashboard đã được cập nhật để phù hợp với ngành mới.',
    'admin.permDashboard': 'Truy cập Dashboard',
    'admin.permReports': 'Xem Báo cáo',
    'admin.permChat': 'AI Chatbot',
    'admin.permSettings': 'Cài đặt Hệ thống',
    'admin.placeholderNote': 'VD: Ghi chú',
    'admin.placeholderDesc': 'VD: Thông tin bổ sung',
    'admin.typeText': 'Text (Chuỗi)',
    'admin.typeNumber': 'Number (Số)',
    'admin.typeDate': 'Date (Ngày tháng)',
    'admin.typeBoolean': 'Boolean (Đúng/Sai)',
    'admin.placeholderDB': 'VD: Database Sản phẩm',
    'admin.dashboardBuilder': 'Trình tạo Dashboard',
    'admin.designPerfectView': 'Thiết kế giao diện hoàn hảo của bạn',
    'admin.industryLabel': 'Ngành:',
    'admin.resetDefault': 'Khôi phục Mặc định',
    'admin.saveLayout': 'Lưu Bố cục',
    'admin.kpiLibrary': 'Thư viện KPI',
    'admin.searchMetrics': 'Tìm kiếm chỉ số...',
    'admin.livePreview': 'Xem trước Trực tiếp',
    'admin.widgetsActive': '{count} tiện ích đang hoạt động',
    'admin.dashboardEmpty': 'Dashboard của bạn đang trống',
    'admin.addKpisToStart': 'Thêm KPI từ thư viện để bắt đầu xây dựng',
    'admin.configSaved': 'Đã lưu cấu hình Dashboard thành công! Dashboard chính đã được cập nhật.',
    'settings.title': 'Cài đặt',
    'settings.desc': 'Tùy chỉnh cấu hình và thông tin doanh nghiệp',
    'settings.agentIdentity': 'Định danh AI',
    'settings.agentName': 'Tên AI',
    'settings.agentLogo': 'Logo AI',
    'settings.uploadLogo': 'Tải logo lên',
    'settings.save': 'Lưu thay đổi',
    'settings.agentNameDesc': 'Tên này sẽ được hiển thị ở thanh bên và giao diện trò chuyện.',
    'settings.personaBehavior': 'Tính cách & Hành vi của AI Agent',
    'settings.commTone': 'Giọng điệu giao tiếp',
    'settings.commToneDesc': 'Xác định cách AI phản hồi các truy vấn của người dùng.',
    'settings.escalationPath': 'Đường dẫn chuyển tiếp',
    'settings.deptGoals': 'Mục tiêu Phòng ban (OKRs)',
    'settings.addGoal': 'Thêm Mục tiêu',
    'settings.current': 'Hiện tại',
    'settings.target': 'Mục tiêu',
    'settings.goalDesc': 'AI Agent sẽ theo dõi các số liệu này và cảnh báo bạn nếu chúng chậm tiến độ.',
    'settings.systemPrefs': 'Tùy chọn Hệ thống',
    'settings.interfaceLang': 'Ngôn ngữ Giao diện',
    'settings.advancedPro': 'Tính năng Nâng cao (Pro)',
    'settings.billing': 'Thanh toán & Đăng ký',
    'settings.billingDesc': 'Quản lý gói Doanh nghiệp, giới hạn sử dụng và phương thức thanh toán của bạn.',
    'settings.apiKeys': 'API Keys & Webhooks',
    'settings.apiKeysDesc': 'Tạo API keys để tích hợp Agent với phần mềm tùy chỉnh bên ngoài.',
    'settings.whitelabel': 'White-labeling',
    'settings.whitelabelDesc': 'Tùy chỉnh logo, màu sắc và tên miền cho khách hàng của bạn.',
    'settings.advancedSecurity': 'Bảo mật Nâng cao',
    'settings.advancedSecurityDesc': 'SSO (SAML/OAuth), Danh sách trắng IP và Nhật ký kiểm tra chi tiết.',
    'settings.placeholderDept': 'VD: Kinh doanh, Nhân sự',
    'settings.placeholderMetric': 'VD: Doanh thu Quý 3',
    'settings.placeholderTarget': 'VD: 50 Tỷ',
    'settings.placeholderCurrent': 'VD: 42 Tỷ',
    'settings.saving': 'Đang lưu Cấu hình...',
    'settings.saveAll': 'Lưu Tất cả Thay đổi',
    'settings.saveSuccess': 'Đã lưu cài đặt thành công!',
    'settings.editGoal': 'Chỉnh sửa Mục tiêu',
    'settings.addNewGoal': 'Thêm Mục tiêu Mới',
    'settings.department': 'Phòng ban',
    'settings.metricDesc': 'Mô tả Số liệu',
    'settings.status': 'Trạng thái',
    'settings.onTrack': 'Đúng tiến độ',
    'settings.atRisk': 'Có nguy cơ',
    'settings.cancel': 'Hủy',
    'settings.saveGoal': 'Lưu Mục tiêu',
    'login.title': 'Đăng nhập',
    'login.email': 'Email',
    'login.password': 'Mật khẩu',
    'login.submit': 'Đăng nhập',
    'login.error': 'Email hoặc mật khẩu không đúng',
    'chatbot.greeting': 'Xin chào! Tôi là {name}. Tôi có thể giúp gì cho bạn?',
    'chatbot.online': 'Trực tuyến',
    'chatbot.suggestedQuestions': 'Câu hỏi gợi ý',
    'chatbot.meetingScheduled': 'Đã lên lịch cuộc họp',
    'chatbot.title': 'Tiêu đề',
    'chatbot.time': 'Thời gian',
    'chatbot.attendees': 'Người tham dự',
    'chatbot.answerFrom': 'Câu trả lời từ {name}',
    'chatbot.nextQuestions': 'Câu hỏi tiếp theo',
    'chatbot.thinking': 'Đang suy nghĩ...',
    'chatbot.uploadData': 'Tải lên tệp dữ liệu (TXT, CSV, JSON)',
    'chatbot.sendMessage': 'Gửi tin nhắn cho {name}...',
    'chatbot.aiWarning': 'AI có thể mắc lỗi. Vui lòng kiểm tra lại thông tin quan trọng.',
    'chatbot.error': 'Xin lỗi, đã có lỗi xảy ra trong quá trình xử lý yêu cầu. Vui lòng kiểm tra API key hoặc thử lại sau.',
    'chatbot.requestedData': 'Đây là dữ liệu bạn yêu cầu:',
  },
  ja: {
    'menu.dashboard': 'ダッシュボード',
    'menu.admin': '管理',
    'menu.settings': '設定',
    'chatbot.title': 'AIビジネスアシスタント',
    'chatbot.placeholder': 'メッセージを入力...',
    'chatbot.send': '送信',
    'home.announcements': '重要なお知らせ',
    'home.todo': 'To-Doリスト',
    'home.calendar': 'カレンダー',
    'home.quickAccess': 'クイックアクセス',
    'home.lineConnect': 'LINE連携',
    'dashboard.finance': '財務',
    'dashboard.operations': '市場と運用',
    'dashboard.hr': '人事とDX',
    'admin.users': 'ユーザー管理',
    'admin.data': 'データとRAG',
    'admin.master': 'マスターデータ',
    'admin.approval': '稟議書',
    'admin.botSettings': 'AIボット設定',
    'admin.integrations': 'アプリ連携',
    'admin.audit': '監査ログ',
    'messages.internal': '社内チャット',
    'messages.feedback': 'お客様の声',
    'messages.emergency': '緊急連絡',
    'messages.files': '共有ファイル',
    'settings.profile': '会社概要',
    'settings.goals': '目標設定',
    'settings.notifications': '通知設定',
    'settings.security': 'セキュリティと多言語',
    'auth.changePassword': 'パスワード変更',
    'auth.logout': 'ログアウト',
    'auth.currentPassword': '現在のパスワード',
    'auth.newPassword': '新しいパスワード',
    'auth.confirmPassword': '新しいパスワード（確認）',
    'auth.cancel': 'キャンセル',
    'auth.update': '更新',
    'auth.passwordMismatch': '新しいパスワードが一致しません。',
    'auth.passwordLength': '新しいパスワードは6文字以上である必要があります。',
    'auth.passwordSuccess': 'パスワードが正常に変更されました！',
    'dashboard.searchAccounts': 'アカウント',
    'dashboard.searchDeals': '取引',
    'dashboard.searchTechFlowEnt': 'TechFlowエンタープライズ',
    'dashboard.searchTechFlowQ3': 'TechFlow第3四半期拡張',
    'login.title': 'Nippon DX Platform',
    'login.subtitle': '管理システムにログイン',
    'login.email': 'メールアドレス',
    'login.password': 'パスワード',
    'login.forgotPassword': 'パスワードをお忘れですか？',
    'login.signIn': 'サインイン',
    'login.signingIn': 'サインイン中...',
    'login.rememberMe': 'ログイン状態を保持する',
    'login.error': 'メールアドレスまたはパスワードが正しくありません',
    'dashboard.proactiveMessage': 'リカバリープランを作成し、リスクのある3つの取引を特定しました。',
    'dashboard.search': '検索...',
    'dashboard.askAgent': 'AIに質問',
    'dashboard.notifications': '通知',
    'dashboard.markAllRead': 'すべて既読にする',
    'dashboard.overview': '概要',
    'dashboard.revenue': '収益',
    'dashboard.pipeline': 'パイプライン',
    'dashboard.accounts': 'アカウント',
    'dashboard.pnl': '損益',
    'dashboard.reports': 'レポート',
    'dashboard.month': '月',
    'dashboard.quarter': '四半期',
    'dashboard.year': '年',
    'dashboard.allTeams': '全チーム',
    'dashboard.allAccounts': '全アカウント',
    'dashboard.keyAccounts': '主要アカウント',
    'dashboard.standardAccounts': '一般アカウント',
    'dashboard.revenueYTD': '年初来収益',
    'dashboard.vsTarget': '目標比',
    'dashboard.pipelineValue': 'パイプライン価値',
    'dashboard.winRate': '勝率',
    'dashboard.activeAccounts': 'アクティブアカウント',
    'dashboard.churnRate': '解約率',
    'dashboard.grossMargin': '粗利益率',
    'dashboard.vsLastYear': '前年比',
    'dashboard.recentActivity': '最近の活動',
    'dashboard.upcomingRenewals': '今後の更新',
    'dashboard.topPerformers': 'トップパフォーマー',
    'dashboard.addWidget': 'ウィジェット追加',
    'dashboard.grossProfit': '粗利益',
    'dashboard.achievement': '達成率',
    'dashboard.growthYoY': '前年比成長',
    'dashboard.wipVsPlan': '実績 vs 計画',
    'dashboard.wipActual': '実績 (WIP)',
    'dashboard.plan': '計画',
    'dashboard.vsLastMonth': '前月比',
    'dashboard.vsPlan': '計画比',
    'dashboard.salesFunnel': 'セールスファネルとパフォーマンス',
    'dashboard.salesPipelineFunnel': 'セールスパイプラインファネル',
    'dashboard.conversionRate': '月別コンバージョン率 (%)',
    'dashboard.perfByLeadSource': 'リードソース別パフォーマンス',
    'dashboard.perfBySalesRep': '営業担当者別パフォーマンス',
    'dashboard.agentInsights': 'エージェントの洞察と推奨アクション',
    'dashboard.updatedAgo': '5分前に更新',
    'dashboard.generateReport': '週次レポートを作成',
    'dashboard.createRecoveryPlan': 'リカバリープランを作成',
    'dashboard.sendFollowUps': 'フォローアップのドラフトを送信',
    'dashboard.simulateRevenueDrop': '収益減少をシミュレート',
    'dashboard.insight1': '12.4M JPYのギャップは、主に大阪エリアでの3件のディールのスリップによるものです。',
    'dashboard.insight2': 'WIP: 7件のディールが次のステップの期限を過ぎています（Kenji Sato: 4件、Yumi Tanaka: 3件）。',
    'dashboard.insight3': 'TechFlow Enterpriseは最新のメールから良い兆候があり、今週中にクローズする可能性があります。',
    'dashboard.notif1Title': 'リスクのあるディール',
    'dashboard.notif1Desc': 'Acme Corp Upgradeの利益率が25%を下回りました。',
    'dashboard.notif1Time': '10分前',
    'dashboard.notif2Title': 'レポート作成完了',
    'dashboard.notif2Desc': '週次セールスレポートの確認準備ができました。',
    'dashboard.notif2Time': '2時間前',
    'dashboard.viewAll': 'すべて表示',
    'dashboard.views.backToDashboard': 'ダッシュボードに戻る',
    'dashboard.views.revenueAnalysis': '収益分析',
    'dashboard.views.month': '月',
    'dashboard.views.quarter': '四半期',
    'dashboard.views.ytd': '年初来',
    'dashboard.views.byTeam': 'チーム別',
    'dashboard.views.byProduct': '製品別',
    'dashboard.views.byAccount': 'アカウント別',
    'dashboard.views.planVsActual': '計画対実績',
    'dashboard.views.segment': 'セグメント',
    'dashboard.views.plan': '計画',
    'dashboard.views.actual': '実績',
    'dashboard.views.gap': 'ギャップ',
    'dashboard.views.attainment': '達成率 (%)',
    'dashboard.views.forecastEOM': '月末予測',
    'dashboard.views.confidence': '信頼度',
    'dashboard.views.gapExplorer': 'ギャップエクスプローラー',
    'dashboard.views.slippedDeals': 'スリップした取引',
    'dashboard.views.reason': '理由',
    'dashboard.views.createTask': 'タスクを作成',
    'dashboard.views.lowPipeline': '低いパイプラインカバレッジ',
    'dashboard.views.target': 'ターゲット',
    'industry.mfg': '製造業',
    'industry.whl': '卸売業',
    'industry.rtl': '小売業',
    'industry.con': '建設業',
    'industry.it': 'IT / ソフトウェア',
    'industry.log': '物流',
    'industry.pro': '専門サービス',
    'industry.hos': 'ホスピタリティ / 飲食',
    'industry.hlt': 'ヘルスケア',
    'industry.real': '不動産',
    'industry.edu': '教育',
    'industry.agr': '農業 / 食品',
    'industry.psv': '個人向けサービス',
    'industry.ecom': 'Eコマース',
    'admin.title': 'システム管理',
    'admin.desc': 'システムの設定と管理。',
    'admin.companyProfile': '会社概要',
    'admin.companyProfileDesc': 'テナント設定と業界の管理',
    'admin.dashboardConfig': 'ダッシュボード設定',
    'admin.dashboardConfigDesc': '業界KPIテンプレートの設定',
    'admin.usersDesc': '役割と権限の管理',
    'admin.dataDesc': 'AIトレーニング用ドキュメントのアップロード',
    'admin.botSettingsDesc': 'AIの動作とトーンの設定',
    'admin.integrationsDesc': 'Line、Kintone、Salesforce',
    'admin.manage': '管理',
    'admin.backToAdmin': '管理に戻る',
    'admin.saveChanges': '変更を保存',
    'admin.cancel': 'キャンセル',
    'admin.companyName': '会社名',
    'admin.industry': '業界',
    'admin.industryWarning': '業界を変更すると、ダッシュボードビルダーの設定がリセットされます。',
    'admin.searchUsers': '名前またはメールでユーザーを検索...',
    'admin.addUser': 'ユーザーを追加',
    'admin.user': 'ユーザー',
    'admin.roleDept': '役割と部門',
    'admin.status': 'ステータス',
    'admin.lastLogin': '最終ログイン',
    'admin.actions': 'アクション',
    'admin.dataSources': 'データソース',
    'admin.agentTraining': 'エージェントトレーニング',
    'admin.dashboardConfigTab': 'ダッシュボード設定',
    'admin.uploadDesc': 'エージェントが学習および分析できるように、ファイルをアップロードするかデータベースに接続します。',
    'admin.connectDB': 'データベース/APIに接続',
    'admin.uploading': 'アップロードと処理中...',
    'admin.uploadData': 'データのアップロード (PDF、CSV、Excel)',
    'admin.dragDrop': 'ここにファイルをドラッグ＆ドロップするか、クリックして選択します。すべての種類のテーブルとドキュメントをサポートします。',
    'admin.dataSourceList': 'データソースリスト',
    'admin.records': 'レコード',
    'admin.trainingDesc': 'エージェントがデータから構造を理解し、抽出する方法を管理します。',
    'admin.retrainAll': 'すべて再トレーニング',
    'admin.source': 'ソース',
    'admin.unknown': '不明',
    'admin.accuracy': '精度',
    'admin.editSchema': 'スキーマを編集',
    'admin.detectedFields': '検出されたデータフィールド:',
    'admin.addField': 'フィールドを追加',
    'admin.mappingDesc': '学習したエージェントデータをダッシュボードテンプレートにマッピングします。',
    'admin.createNewMapping': '新しいマッピングを作成',
    'admin.autoMap': '自動マップ',
    'admin.sync': '同期',
    'admin.integrationsDesc': 'サードパーティのアプリケーションを接続してデータを同期し、クロスプラットフォーム機能を有効にします。',
    'admin.connect': '接続',
    'admin.disconnect': '切断',
    'admin.aiAgentStudio': 'AIエージェントスタジオ',
    'admin.aiAgentDesc': '専門的なAIエージェント、その知識、および動作を管理します。',
    'admin.createAgent': 'エージェントを作成',
    'admin.tasksAutomated': '自動化されたタスク',
    'admin.proactiveTriggers': 'プロアクティブトリガー',
    'admin.proactiveDesc': '受動的なチャットボットとは異なり、当社のエージェントはデータを監視し、自動的にアクションを開始します。',
    'admin.configureTriggers': 'トリガーを設定',
    'admin.jpContextTuning': '日本語コンテキストチューニング',
    'admin.keigoLevel': '敬語レベル (デフォルト)',
    'admin.industryJargon': '業界用語',
    'admin.editUser': 'ユーザーを編集',
    'admin.addNewUser': '新規ユーザーを追加',
    'admin.fullName': '氏名',
    'admin.emailAddress': 'メールアドレス',
    'admin.department': '部署',
    'admin.role': '役割',
    'admin.status': 'ステータス',
    'admin.resetPassword': 'パスワードをリセット (任意)',
    'admin.initialPassword': '初期パスワード',
    'admin.leaveBlank': '変更しない場合は空白',
    'admin.enterPassword': 'パスワードを入力',
    'admin.modulePermissions': 'モジュール権限',
    'admin.adminAccessNote': '管理者は自動的にすべてのモジュールへのフルアクセス権を持ちます。',
    'admin.saveUser': 'ユーザーを保存',
    'admin.cancel': 'キャンセル',
    'admin.connectDBAPI': 'データベース/APIを接続',
    'admin.connectionType': '接続タイプ',
    'admin.displayName': '表示名',
    'admin.connectionString': '接続文字列 / URL',
    'admin.connectBtn': '接続',
    'admin.addSchemaField': 'スキーマフィールドを追加',
    'admin.fieldName': 'フィールド名',
    'admin.fieldType': 'データ型',
    'admin.description': '説明',
    'admin.addBtn': '追加',
    'admin.createMapping': 'マッピングを作成',
    'admin.selectSchema': 'スキーマを選択',
    'admin.selectTemplate': 'テンプレートを選択',
    'admin.createBtn': '作成',
    'admin.companySaved': '会社設定が正常に保存されました。ダッシュボードのKPIが新しい業界に合わせて更新されました。',
    'admin.permDashboard': 'ダッシュボードへのアクセス',
    'admin.permReports': 'レポートの表示',
    'admin.permChat': 'AIチャットボット',
    'admin.permSettings': 'システム設定',
    'admin.placeholderNote': '例：備考',
    'admin.placeholderDesc': '例：追加情報',
    'admin.typeText': 'テキスト (文字列)',
    'admin.typeNumber': '数値 (数字)',
    'admin.typeDate': '日付 (年月日)',
    'admin.typeBoolean': 'ブール値 (真/偽)',
    'admin.placeholderDB': '例：製品データベース',
    'admin.dashboardBuilder': 'ダッシュボードビルダー',
    'admin.designPerfectView': '完璧なビューをデザインする',
    'admin.industryLabel': '業界:',
    'admin.resetDefault': 'デフォルトにリセット',
    'admin.saveLayout': 'レイアウトを保存',
    'admin.kpiLibrary': 'KPIライブラリ',
    'admin.searchMetrics': '指標を検索...',
    'admin.livePreview': 'ライブプレビュー',
    'admin.widgetsActive': '{count}個のウィジェットがアクティブ',
    'admin.dashboardEmpty': 'ダッシュボードは空です',
    'admin.addKpisToStart': 'ライブラリからKPIを追加して構築を開始します',
    'admin.configSaved': 'ダッシュボード構成が正常に保存されました！メインダッシュボードが更新されました。',
    'settings.title': '設定',
    'settings.desc': '会社情報とシステム設定のカスタマイズ',
    'settings.agentIdentity': 'AIアイデンティティ',
    'settings.agentName': 'AI名',
    'settings.agentLogo': 'AIロゴ',
    'settings.uploadLogo': 'ロゴをアップロード',
    'settings.save': '変更を保存',
    'settings.agentNameDesc': 'この名前はサイドバーとチャットインターフェースに表示されます。',
    'settings.personaBehavior': 'AIエージェントのペルソナと行動',
    'settings.commTone': 'コミュニケーションのトーン',
    'settings.commToneDesc': 'AIがユーザーのクエリにどのように応答するかを決定します。',
    'settings.escalationPath': 'エスカレーションパス',
    'settings.deptGoals': '部門の目標 (OKRs)',
    'settings.addGoal': '目標を追加',
    'settings.current': '現在',
    'settings.target': '目標',
    'settings.goalDesc': 'AIエージェントはこれらの指標を監視し、予定より遅れている場合は警告します。',
    'settings.systemPrefs': 'システム環境設定',
    'settings.interfaceLang': 'インターフェース言語',
    'settings.advancedPro': '高度な機能 (Pro)',
    'settings.billing': '請求とサブスクリプション',
    'settings.billingDesc': 'エンタープライズプラン、使用制限、支払い方法を管理します。',
    'settings.apiKeys': 'APIキーとWebhook',
    'settings.apiKeysDesc': 'エージェントを外部のカスタムソフトウェアと統合するためのAPIキーを生成します。',
    'settings.whitelabel': 'ホワイトレーベル',
    'settings.whitelabelDesc': 'クライアント向けにロゴ、色、ドメインをカスタマイズします。',
    'settings.advancedSecurity': '高度なセキュリティ',
    'settings.advancedSecurityDesc': 'SSO (SAML/OAuth)、IPホワイトリスト、および詳細な監査ログ。',
    'settings.placeholderDept': '例：営業、人事',
    'settings.placeholderMetric': '例：第3四半期の収益',
    'settings.placeholderTarget': '例：5000万円',
    'settings.placeholderCurrent': '例：4200万円',
    'settings.saving': '設定を保存中...',
    'settings.saveAll': 'すべての変更を保存',
    'settings.saveSuccess': '設定が正常に保存されました！',
    'settings.editGoal': '目標を編集',
    'settings.addNewGoal': '新しい目標を追加',
    'settings.department': '部門',
    'settings.metricDesc': '指標の説明',
    'settings.status': 'ステータス',
    'settings.onTrack': '順調',
    'settings.atRisk': 'リスクあり',
    'settings.cancel': 'キャンセル',
    'settings.saveGoal': '目標を保存',
    'login.title': 'ログイン',
    'login.email': 'メールアドレス',
    'login.password': 'パスワード',
    'login.submit': 'ログイン',
    'login.error': 'メールアドレスまたはパスワードが正しくありません',
    'chatbot.greeting': 'こんにちは！私は {name} です。何かお手伝いしましょうか？',
    'chatbot.online': 'オンライン',
    'chatbot.suggestedQuestions': 'おすすめの質問',
    'chatbot.meetingScheduled': 'ミーティング予約完了',
    'chatbot.title': 'タイトル',
    'chatbot.time': '日時',
    'chatbot.attendees': '参加者',
    'chatbot.answerFrom': '{name} からの回答',
    'chatbot.nextQuestions': '次の質問の候補',
    'chatbot.thinking': '考え中...',
    'chatbot.uploadData': 'データファイルをアップロード (TXT, CSV, JSON)',
    'chatbot.sendMessage': '{name} にメッセージを送信...',
    'chatbot.aiWarning': 'AIは間違いを犯す可能性があります。重要な情報は確認してください。',
    'chatbot.error': '申し訳ありませんが、リクエストの処理中にエラーが発生しました。APIキーを確認するか、後でもう一度お試しください。',
    'chatbot.requestedData': 'リクエストされたデータはこちらです：',
  },
  en: {
    'menu.dashboard': 'Dashboard',
    'menu.admin': 'Admin',
    'menu.settings': 'Settings',
    'chatbot.title': 'AI Business Agent',
    'chatbot.placeholder': 'Type a message...',
    'chatbot.send': 'Send',
    'home.announcements': 'Announcements',
    'home.todo': 'To-do List',
    'home.calendar': 'Calendar',
    'home.quickAccess': 'Quick Access',
    'home.lineConnect': 'Line Integration',
    'dashboard.finance': 'Finance',
    'dashboard.operations': 'Operations & Market',
    'dashboard.hr': 'HR & DX',
    'admin.users': 'Users Management',
    'admin.data': 'Data & RAG',
    'admin.master': 'Master Data',
    'admin.approval': 'Approval Flows',
    'admin.botSettings': 'AI Bot Settings',
    'admin.integrations': 'App Integrations',
    'admin.audit': 'Audit Logs',
    'messages.internal': 'Internal Chat',
    'messages.feedback': 'Customer Feedback',
    'messages.emergency': 'Emergency Alerts',
    'messages.files': 'Shared Files',
    'settings.profile': 'Company Profile',
    'settings.goals': 'Goal Setting',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security & Language',
    'auth.changePassword': 'Change Password',
    'auth.logout': 'Logout',
    'auth.currentPassword': 'Current Password',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm New Password',
    'auth.cancel': 'Cancel',
    'auth.update': 'Update',
    'auth.passwordMismatch': 'New passwords do not match.',
    'auth.passwordLength': 'New password must be at least 6 characters.',
    'auth.passwordSuccess': 'Password changed successfully!',
    'dashboard.searchAccounts': 'Accounts',
    'dashboard.searchDeals': 'Deals',
    'dashboard.searchTechFlowEnt': 'TechFlow Enterprise',
    'dashboard.searchTechFlowQ3': 'TechFlow Q3 Expansion',
    'login.title': 'Nippon DX Platform',
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.signIn': 'Sign in',
    'login.signingIn': 'Signing in...',
    'login.rememberMe': 'Remember me',
    'login.error': 'Invalid email or password',
    'dashboard.proactiveMessage': 'I\'ve prepared a recovery plan and identified 3 at-risk deals.',
    'dashboard.search': 'Search...',
    'dashboard.askAgent': 'Ask AI',
    'dashboard.notifications': 'Notifications',
    'dashboard.markAllRead': 'Mark all as read',
    'dashboard.overview': 'Overview',
    'dashboard.revenue': 'Revenue',
    'dashboard.pipeline': 'Pipeline',
    'dashboard.accounts': 'Accounts',
    'dashboard.pnl': 'P&L',
    'dashboard.reports': 'Reports',
    'dashboard.month': 'Month',
    'dashboard.quarter': 'Quarter',
    'dashboard.year': 'Year',
    'dashboard.allTeams': 'All Teams',
    'dashboard.allAccounts': 'All Accounts',
    'dashboard.keyAccounts': 'Key Accounts',
    'dashboard.standardAccounts': 'Standard Accounts',
    'dashboard.revenueYTD': 'Revenue YTD',
    'dashboard.vsTarget': 'vs Target',
    'dashboard.pipelineValue': 'Pipeline Value',
    'dashboard.winRate': 'Win Rate',
    'dashboard.activeAccounts': 'Active Accounts',
    'dashboard.churnRate': 'Churn Rate',
    'dashboard.grossMargin': 'Gross Margin',
    'dashboard.vsLastYear': 'vs Last Year',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.upcomingRenewals': 'Upcoming Renewals',
    'dashboard.topPerformers': 'Top Performers',
    'dashboard.addWidget': 'Add Widget',
    'dashboard.grossProfit': 'Gross Profit',
    'dashboard.achievement': '% Achievement',
    'dashboard.growthYoY': 'Growth YoY',
    'dashboard.wipVsPlan': 'WIP vs Plan Comparison',
    'dashboard.wipActual': 'WIP (Actual)',
    'dashboard.plan': 'Plan',
    'dashboard.vsLastMonth': 'vs last month',
    'dashboard.vsPlan': 'vs plan',
    'dashboard.salesFunnel': 'Sales Funnel & Performance',
    'dashboard.salesPipelineFunnel': 'Sales Pipeline Funnel',
    'dashboard.conversionRate': 'Conversion Rate by Month (%)',
    'dashboard.perfByLeadSource': 'Performance by Lead Source',
    'dashboard.perfBySalesRep': 'Performance by Sales Rep',
    'dashboard.agentInsights': 'Agent Insights & Recommended Actions',
    'dashboard.updatedAgo': 'Updated 5m ago',
    'dashboard.generateReport': 'Generate Weekly Report',
    'dashboard.createRecoveryPlan': 'Create Recovery Plan',
    'dashboard.sendFollowUps': 'Send Follow-up Drafts',
    'dashboard.simulateRevenueDrop': 'Simulate Revenue Drop',
    'dashboard.insight1': '12.4M JPY gap is mainly due to 3 slipped deals in the Osaka area.',
    'dashboard.insight2': 'WIP: 7 deals are overdue for the next step (Kenji Sato: 4, Yumi Tanaka: 3).',
    'dashboard.insight3': 'TechFlow Enterprise shows positive signals from the latest email, likely to close this week.',
    'dashboard.notif1Title': 'Deal at Risk',
    'dashboard.notif1Desc': 'Acme Corp Upgrade margin dropped below 25%.',
    'dashboard.notif1Time': '10 mins ago',
    'dashboard.notif2Title': 'Report Generated',
    'dashboard.notif2Desc': 'Weekly Sales Report is ready for review.',
    'dashboard.notif2Time': '2 hours ago',
    'dashboard.viewAll': 'View All',
    'dashboard.views.backToDashboard': 'Back to Dashboard',
    'dashboard.views.revenueAnalysis': 'Revenue Analysis',
    'dashboard.views.month': 'Month',
    'dashboard.views.quarter': 'Quarter',
    'dashboard.views.ytd': 'YTD',
    'dashboard.views.byTeam': 'By Team',
    'dashboard.views.byProduct': 'By Product',
    'dashboard.views.byAccount': 'By Account',
    'dashboard.views.planVsActual': 'Plan vs Actual',
    'dashboard.views.segment': 'Segment',
    'dashboard.views.plan': 'Plan',
    'dashboard.views.actual': 'Actual',
    'dashboard.views.gap': 'Gap',
    'dashboard.views.attainment': '% Attainment',
    'dashboard.views.forecastEOM': 'Forecast EOM',
    'dashboard.views.confidence': 'Confidence',
    'dashboard.views.gapExplorer': 'Gap Explorer',
    'dashboard.views.slippedDeals': 'Slipped Deals',
    'dashboard.views.reason': 'Reason',
    'dashboard.views.createTask': 'Create Task',
    'dashboard.views.lowPipeline': 'Low Pipeline Coverage',
    'dashboard.views.target': 'Target',
    'industry.mfg': 'Manufacturing',
    'industry.whl': 'Wholesale',
    'industry.rtl': 'Retail',
    'industry.con': 'Construction',
    'industry.it': 'IT / Software',
    'industry.log': 'Logistics',
    'industry.pro': 'Professional Services',
    'industry.hos': 'Hospitality / F&B',
    'industry.hlt': 'Healthcare',
    'industry.real': 'Real Estate',
    'industry.edu': 'Education',
    'industry.agr': 'Agriculture / Food',
    'industry.psv': 'Personal Services',
    'industry.ecom': 'E-commerce',
    'admin.title': 'System Administration',
    'admin.desc': 'System configuration and management.',
    'admin.companyProfile': 'Company Profile',
    'admin.companyProfileDesc': 'Manage tenant settings and industry',
    'admin.dashboardConfig': 'Dashboard Config',
    'admin.dashboardConfigDesc': 'Configure industry KPI templates',
    'admin.usersDesc': 'Manage roles and permissions',
    'admin.dataDesc': 'Upload documents for AI training',
    'admin.botSettingsDesc': 'Configure AI behavior and tone',
    'admin.integrationsDesc': 'Line, Kintone, Salesforce',
    'admin.manage': 'Manage',
    'admin.backToAdmin': 'Back to Admin',
    'admin.saveChanges': 'Save Changes',
    'admin.cancel': 'Cancel',
    'admin.companyName': 'Company Name',
    'admin.industry': 'Industry',
    'admin.industryWarning': 'Changing the industry will reset the Dashboard Builder configuration.',
    'admin.searchUsers': 'Search users by name or email...',
    'admin.addUser': 'Add User',
    'admin.user': 'User',
    'admin.roleDept': 'Role & Dept',
    'admin.status': 'Status',
    'admin.lastLogin': 'Last Login',
    'admin.actions': 'Actions',
    'admin.dataSources': 'Data Sources',
    'admin.agentTraining': 'Agent Training',
    'admin.dashboardConfigTab': 'Dashboard Config',
    'admin.uploadDesc': 'Upload files or connect to a database so the Agent can learn and analyze.',
    'admin.connectDB': 'Connect Database/API',
    'admin.uploading': 'Uploading & Processing...',
    'admin.uploadData': 'Upload Data (PDF, CSV, Excel)',
    'admin.dragDrop': 'Drag and drop files here or click to select. Supports all types of tables and documents.',
    'admin.dataSourceList': 'Data Source List',
    'admin.records': 'records',
    'admin.trainingDesc': 'Manage how the Agent understands and extracts structure from your data.',
    'admin.retrainAll': 'Retrain All',
    'admin.source': 'Source',
    'admin.unknown': 'Unknown',
    'admin.accuracy': 'Accuracy',
    'admin.editSchema': 'Edit Schema',
    'admin.detectedFields': 'Detected Data Fields:',
    'admin.addField': 'Add Field',
    'admin.mappingDesc': 'Map learned Agent data to Dashboard Templates.',
    'admin.createNewMapping': 'Create New Mapping',
    'admin.autoMap': 'Auto Map',
    'admin.sync': 'Sync',
    'admin.integrationsDesc': 'Connect third-party applications to sync data and enable cross-platform features.',
    'admin.connect': 'Connect',
    'admin.disconnect': 'Disconnect',
    'admin.aiAgentStudio': 'AI Agent Studio',
    'admin.aiAgentDesc': 'Manage specialized AI agents, their knowledge, and behaviors.',
    'admin.createAgent': 'Create Agent',
    'admin.tasksAutomated': 'tasks automated',
    'admin.proactiveTriggers': 'Proactive Triggers',
    'admin.proactiveDesc': 'Unlike passive chatbots, our agents monitor your data and initiate actions automatically.',
    'admin.configureTriggers': 'Configure Triggers',
    'admin.jpContextTuning': 'Japanese Context Tuning',
    'admin.keigoLevel': 'Keigo Level (Default)',
    'admin.industryJargon': 'Industry Jargon',
    'admin.editUser': 'Edit User',
    'admin.addNewUser': 'Add New User',
    'admin.fullName': 'Full Name',
    'admin.emailAddress': 'Email Address',
    'admin.department': 'Department',
    'admin.role': 'Role',
    'admin.status': 'Status',
    'admin.resetPassword': 'Reset Password (Optional)',
    'admin.initialPassword': 'Initial Password',
    'admin.leaveBlank': 'Leave blank to keep current',
    'admin.enterPassword': 'Enter password',
    'admin.modulePermissions': 'Module Permissions',
    'admin.adminAccessNote': 'Admins have full access to all modules automatically.',
    'admin.saveUser': 'Save User',
    'admin.cancel': 'Cancel',
    'admin.connectDBAPI': 'Connect Database/API',
    'admin.connectionType': 'Connection Type',
    'admin.displayName': 'Display Name',
    'admin.connectionString': 'Connection String / URL',
    'admin.connectBtn': 'Connect',
    'admin.addSchemaField': 'Add Schema Field',
    'admin.fieldName': 'Field Name',
    'admin.fieldType': 'Data Type',
    'admin.description': 'Description',
    'admin.addBtn': 'Add',
    'admin.createMapping': 'Create Mapping',
    'admin.selectSchema': 'Select Schema',
    'admin.selectTemplate': 'Select Template',
    'admin.createBtn': 'Create',
    'admin.companySaved': 'Company settings saved successfully. Dashboard KPIs have been updated to match the new industry.',
    'admin.permDashboard': 'Dashboard Access',
    'admin.permReports': 'View Reports',
    'admin.permChat': 'AI Chatbot',
    'admin.permSettings': 'System Settings',
    'admin.placeholderNote': 'e.g., Notes',
    'admin.placeholderDesc': 'e.g., Additional information',
    'admin.typeText': 'Text (String)',
    'admin.typeNumber': 'Number',
    'admin.typeDate': 'Date',
    'admin.typeBoolean': 'Boolean (True/False)',
    'admin.placeholderDB': 'e.g., Product Database',
    'admin.dashboardBuilder': 'Dashboard Builder',
    'admin.designPerfectView': 'Design your perfect view',
    'admin.industryLabel': 'Industry:',
    'admin.resetDefault': 'Reset to Default',
    'admin.saveLayout': 'Save Layout',
    'admin.kpiLibrary': 'KPI Library',
    'admin.searchMetrics': 'Search metrics...',
    'admin.livePreview': 'Live Preview',
    'admin.widgetsActive': '{count} widgets active',
    'admin.dashboardEmpty': 'Your dashboard is empty',
    'admin.addKpisToStart': 'Add KPIs from the library to start building',
    'admin.configSaved': 'Dashboard configuration saved successfully! The main dashboard has been updated.',
    'settings.title': 'Settings',
    'settings.desc': 'Customize company profile and system settings',
    'settings.agentIdentity': 'Agent Identity',
    'settings.agentName': 'Agent Name',
    'settings.agentLogo': 'Agent Logo',
    'settings.uploadLogo': 'Upload Logo',
    'settings.save': 'Save Changes',
    'settings.agentNameDesc': 'This name will be displayed in the sidebar and chat interface.',
    'settings.personaBehavior': 'AI Agent Persona & Behavior',
    'settings.commTone': 'Communication Tone',
    'settings.commToneDesc': 'Determines how the AI responds to user queries.',
    'settings.escalationPath': 'Escalation Path',
    'settings.deptGoals': 'Department Goals (OKRs)',
    'settings.addGoal': 'Add Goal',
    'settings.current': 'Current',
    'settings.target': 'Target',
    'settings.goalDesc': 'The AI Agent will monitor these metrics and alert you if they fall behind schedule.',
    'settings.systemPrefs': 'System Preferences',
    'settings.interfaceLang': 'Interface Language',
    'settings.advancedPro': 'Advanced Features (Pro)',
    'settings.billing': 'Billing & Subscription',
    'settings.billingDesc': 'Manage your Enterprise plan, usage limits, and payment methods.',
    'settings.apiKeys': 'API Keys & Webhooks',
    'settings.apiKeysDesc': 'Generate API keys to integrate the Agent with external custom software.',
    'settings.whitelabel': 'White-labeling',
    'settings.whitelabelDesc': 'Customize logos, colors, and domain for your clients.',
    'settings.advancedSecurity': 'Advanced Security',
    'settings.advancedSecurityDesc': 'SSO (SAML/OAuth), IP Whitelisting, and detailed Audit Logs.',
    'settings.placeholderDept': 'e.g., Sales, HR',
    'settings.placeholderMetric': 'e.g., Q3 Revenue',
    'settings.placeholderTarget': 'e.g., ¥50M',
    'settings.placeholderCurrent': 'e.g., ¥42M',
    'settings.saving': 'Saving Configuration...',
    'settings.saveAll': 'Save All Changes',
    'settings.saveSuccess': 'Settings saved successfully!',
    'settings.editGoal': 'Edit Goal',
    'settings.addNewGoal': 'Add New Goal',
    'settings.department': 'Department',
    'settings.metricDesc': 'Metric Description',
    'settings.status': 'Status',
    'settings.onTrack': 'On Track',
    'settings.atRisk': 'At Risk',
    'settings.cancel': 'Cancel',
    'settings.saveGoal': 'Save Goal',
    'login.title': 'Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.error': 'Invalid email or password',
    'chatbot.greeting': 'Hello! I am {name}. How can I help you?',
    'chatbot.online': 'Online',
    'chatbot.suggestedQuestions': 'Suggested Questions',
    'chatbot.meetingScheduled': 'Meeting Scheduled',
    'chatbot.title': 'Title',
    'chatbot.time': 'Time',
    'chatbot.attendees': 'Attendees',
    'chatbot.answerFrom': 'Answer from {name}',
    'chatbot.nextQuestions': 'Suggested next questions',
    'chatbot.thinking': 'Thinking...',
    'chatbot.uploadData': 'Upload data file (TXT, CSV, JSON)',
    'chatbot.sendMessage': 'Send a message to {name}...',
    'chatbot.aiWarning': 'AI can make mistakes. Please verify important information.',
    'chatbot.error': 'Sorry, an error occurred while processing your request. Please check your API key or try again later.',
    'chatbot.requestedData': 'Here is the requested data:',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ja');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
